server:
    port: 8080
spring:
    datasource:
        driver-class-name: oracle.jdbc.driver.OracleDriver
        url: jdbc:oracle:thin:@139.196.101.174:1521:orcl
        username: MainDatabaseOfProcess
        password: maindatabaseofprocess       
        type: com.alibaba.druid.pool.DruidDataSource
        
        #默认无法使用以下属性，需要config配置类来配置属性
        initialSize: 5
        minIdle: 5
        maxActive: 20
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatement: true
        #配置监控统计的filters,去掉监控界面sql无法统计，“wall”用于防火墙
        filters: stat,wall
        maxPoolPreparedStatementPerConnectionSize: 20
        useGlobalDataSourceStat: true
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slow.slowSqlMillis=500
logging:
    level: 
        com.example.dataprocess.mapper: debug


